name: phonami
favicon: null
layout_spectrum: 0.34127
typography_spectrum: 0.65282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e5bc7'
    - '#ffffff'
    - '#9cabe1'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.9230522378347814
  lightness: 0.05697018187493086
  saturation: 0.10682080942206085
  rhythmicContrast: 0.7828586455434561
purpose: []
