name: phonami
favicon: null
layout_spectrum: 0.2865284823346883
typography_spectrum: 0.594155375380069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9230522378347814
  lightness: 0.05697018187493086
  saturation: 0.10682080942206085
  rhythmicContrast: 0.7828586455434561
purpose: []
