name: phonami
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73493
title: phonami.grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53429779-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e5bc7'
    - '#ffffff'
    - '#9cabe1'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.9375
  lightness: 0.05697018187493086
  saturation: 0.10682080942206085
  rhythmicContrast: 0.7828586455434561
purpose: []
